name: Release to Maven Central

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release version (optional - defaults to removing -SNAPSHOT)'
        required: false
      developmentVersion:
        description: 'Next development version (optional - defaults to incrementing patch)'
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
      MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      MAVEN_RELEASE_TOKEN: ${{secrets.MAVEN_RELEASE_TOKEN}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          token: ${{ env.MAVEN_RELEASE_TOKEN }}

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'liberica'
          cache: 'maven'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ env.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Configure Git
        run: |
          git config user.name "Prasanna Kumar Ramachandran"
          git config user.email "prasanna0586@gmail.com"

      - name: Prepare Release
        run: |
          if [ -n "${{ github.event.inputs.releaseVersion }}" ] && [ -n "${{ github.event.inputs.developmentVersion }}" ]; then
            mvn --batch-mode release:prepare \
              -DreleaseVersion=${{ github.event.inputs.releaseVersion }} \
              -DdevelopmentVersion=${{ github.event.inputs.developmentVersion }}
          else
            mvn --batch-mode release:prepare
          fi

      - name: Perform Release
        run: mvn --batch-mode release:perform
